
FROM python:3.9-windowsservercore

# Instalar dependencias
RUN pip install --no-cache-dir pyinstaller

WORKDIR C:/app

# Copiar solo los archivos necesarios para instalar dependencias
COPY requirements.txt .

# Instalar dependencias de Python
RUN pip install --no-cache-dir -r requirements.txt
